use lib '../lib';
use strict;
use Test::More tests => 12;
use WRE::Config;
use WRE::Mysql;

my $wreConfig = WRE::Config->new();
my $mysql = WRE::Mysql->new(wreConfig=>$wreConfig);
isa_ok($mysql, "WRE::Mysql");
is($mysql->ping, 0, "MySQL is supposed to be down.");
isnt($mysql->ping, 1, "MySQL is supposed to be down. False positive.");
is($mysql->start, 1, "Start mysql.");
isnt($mysql->ping, 0, "MySQL is supposed to be up. False negative.");
is($mysql->ping, 1, "MySQL is supposed to be up.");
is($mysql->restart, 1, "Restart mysql.");
is($mysql->ping, 1, "MySQL is supposed to be up.");
isa_ok($mysql->getDatabaseHandle(password=>"test", username=>"test", dsn=>"DBI:mysql:test"), "DBI::db");
is(eval{$mysql->isAdmin(password=>"xxxxxx")},undef,"Can't log in with an invalid password.");
is($mysql->stop, 1, "Stop mysql.");
is($mysql->ping, 0, "MySQL is supposed to be down.");
