#!/data/wre/prereqs/perl/bin/perl -w
use strict;
use DBI;
use Parse::PlainConfig;
use File::Path;

my $config = Parse::PlainConfig->new('DELIM' => '=', 'FILE' => '/data/wre/etc/demo.conf', 'PURGE' => 1);
my $dbh = DBI->connect("DBI:mysql:test;host=".$config->get("mysqlhost"),$config->get("adminuser"),$config->get("adminpass"));
my $demos = $config->get('sites');
my %newDemos = ();
foreach my $demoId (keys %{$demos}) {
	next unless ($demoId); # prevent empty strings from wreaking havoc
	if (time() - $demos->{$demoId} > $config->get("duration") * 60 * 60 * 24) {
		$dbh->do("drop database ".$demoId);
		$dbh->do("revoke all privileges on ".$demoId.".* from demo\@localhost");
		rmtree("/data/domains/demo/".$demoId);	
		unlink("/data/WebGUI/etc/".$demoId.".conf");
	} else {
		$newDemos{$demoId} = $demos->{$demoId};
	}
}
$dbh->disconnect;
$config->set('sites'=>\%newDemos);
$config->write;

