#!/bin/bash
# chkconfig: 2345 90 60
# description: Start and stop WebGUI (WRE) related services
# processname: webgui

. /data/wre/sbin/setenvironment.sh

# See how we were called.
case "$1" in
  	start)
   		/data/wre/sbin/wreservice.pl --quiet --start all
    	;;
  	stop)
    	/data/wre/sbin/wreservice.pl --quiet --stop all
    	;;
  	restart)
    	/data/wre/sbin/wreservice.pl --quiet --restart all
    	;;
  	startmysql)
    	/data/wre/sbin/wreservice.pl --quiet --start mysql
    	;;
  	stopmysql)
		/data/wre/sbin/wreservice.pl --quiet --stop mysql
    	;;
  	restartmysql)
    	/data/wre/sbin/wreservice.pl --quiet --restart mysql
    	;;
  	startweb)
    	/data/wre/sbin/wreservice.pl --quiet --start web
    	;;
  	stopweb)
    	/data/wre/sbin/wreservice.pl --quiet --stop web
    	;;
  	restartweb)
    	/data/wre/sbin/wreservice.pl --quiet --restart web
    	;;
  	startstarman)
    	/data/wre/sbin/wreservice.pl --quiet --start starman
    	;;
  	stopstarman)
    	/data/wre/sbin/wreservice.pl --quiet --stop starman
    	;;
  	restartstarman)
    	/data/wre/sbin/wreservice.pl --quiet --restart starman
    	;;
  	startnginx)
    	/data/wre/sbin/wreservice.pl --quiet --start nginx
    	;;
  	stopnginx)
    	/data/wre/sbin/wreservice.pl --quiet --stop nginx
    	;;
  	restartnginx)
    	/data/wre/sbin/wreservice.pl --quiet --restart nginx
    	;;
  	startspectre)
    	/data/wre/sbin/wreservice.pl --quiet --start spectre
    	;;
  	stopspectre)
    	/data/wre/sbin/wreservice.pl --quiet --stop spectre
    	;;
  	restartspectre)
    	/data/wre/sbin/wreservice.pl --quiet --restart spectre
    	;;
  	*)
		echo $"WRE Service Controller"
   		echo $"Usage:"
		echo $"	$0 { start | stop | restart }"
		echo $"	$0 { startweb | stopweb | restartweb }"
   		echo $"	$0 { startstarman | stopstarman | restartstarman }"
   		echo $"	$0 { startnginx | stopnginx | restartnginx }"
   		echo $"	$0 { startmysql | stopmysql | restartmysql }"
   		echo $"	$0 { startspectre | stopspectre | restartspectre }"
   		exit 1
esac

exit $?
