#!/bin/bash
# chkconfig: 2345 90 60
# description: Start and stop WebGUI (WRE) Spectre
# processname: wrespectre

. /data/wre/sbin/setenvironment.sh

# See how we were called.
case "$1" in
  	start)
   		/data/wre/sbin/wreservice.pl --quiet --start spectre
    	;;
  	stop)
    	/data/wre/sbin/wreservice.pl --quiet --stop spectre
    	;;
  	restart)
    	/data/wre/sbin/wreservice.pl --quiet --restart spectre
    	;;
  	*)
		echo $"WRE Spectre Service Controller"
   		echo $"Usage:"
		echo $"	$0 { start | stop | restart }"
    	exit 1
esac

exit $?
