#!/bin/bash
# chkconfig: 2345 90 60
# description: Start and stop WebGUI (WRE) Apache
# processname: wreapache

. /data/wre/sbin/setenvironment.sh

# See how we were called.
case "$1" in
  	start)
   		/data/wre/sbin/wreservice.pl --quiet --start web
    	;;
  	stop)
    	/data/wre/sbin/wreservice.pl --quiet --stop web
    	;;
  	restart)
    	/data/wre/sbin/wreservice.pl --quiet --restart web
    	;;
  	startmodperl)
    	/data/wre/sbin/wreservice.pl --quiet --start modperl
    	;;
  	stopmodperl)
    	/data/wre/sbin/wreservice.pl --quiet --stop modperl
    	;;
  	restartmodperl)
    	/data/wre/sbin/wreservice.pl --quiet --restart modperl
    	;;
  	startnginx)
    	/data/wre/sbin/wreservice.pl --quiet --start nginx
    	;;
  	stopnginx)
    	/data/wre/sbin/wreservice.pl --quiet --stop nginx
    	;;
  	restartnginx)
    	/data/wre/sbin/wreservice.pl --quiet --restart nginx
    	;;
  	*)
		echo $"WRE Apache Service Controller"
   		echo $"Usage:"
		echo $"	$0 { start | stop | restart }"
   		echo $"	$0 { startmodperl | stopmodperl | restartmodperl }"
   		echo $"	$0 { startnginx | stopnginx | restartnginx }"
   		echo $"	$0 { startweb | stopweb | restartweb }"
    	exit 1
esac

exit $?
