#!/bin/bash
# chkconfig: 2345 90 60
# description: Start and stop WebGUI (WRE) Apache
# processname: wremysql

. /data/wre/sbin/setenvironment.sh

# See how we were called.
case "$1" in
  	start)
   		/data/wre/sbin/wreservice.pl --quiet --start mysql
    	;;
  	stop)
    	/data/wre/sbin/wreservice.pl --quiet --stop mysql
    	;;
  	restart)
    	/data/wre/sbin/wreservice.pl --quiet --restart mysql
    	;;
  	*)
		echo $"WRE MySQL Service Controller"
   		echo $"Usage:"
		echo $"	$0 { start | stop | restart }"
    	exit 1
esac

exit $?
