=head1 NAME

wre.conf - Configuration file for the WebGUI Runtime Environment

=head1 DESCRIPTION

This wre script backups all files and databases according to the wre.conf and
backup.exclude files. This script is advised to be run as a root cronjob. All
options in the configuration files will be discussed.

=head1 CONFIGURATION

The configuration file is stored as JSON.

=head2 BACKUP

   "backup" : {
      "enabled" : "1",
      "externalScripts" : [],
      "rsync" : {
         "enabled" : "1",
         "hostname" : "my remote backup host",
         "path" : "/remote_backups",
         "rotations" : "1",
         "user" : "username"
      },
      "items" : {  ##List of directories to backup, wildcards are okay
		    "/data/domains",  ##All domain files
		    "/data/WebGUI",   ##All of WebGUI, including etc and sbin
		    "/data/backup/*.sql.gz",  ##All database dumps
		    "/data/wre/etc"  ##All WRE configuration files
      },
      "mysql" : {
         "password" : "also_sekrit",
         "user" : "other_name"
      },
      "path" : "/backup",
   },

=over 4

=item B<enabled>

This value has to be non-zero to enable backups for this instance.

=item B<externalScripts>

Optional value that can be set to run external script during backup.

=item B<items>

A list of directories that should be backed up.  They are copied to B<path> and optionally transferred remotely.

=item B<path>

The path to the directory on the WebGUI host, where the backups are stored.

=back

=head3 RSYNC OPTIONS

Rsync based backups require that private/public key-pair be setup for transfers.

=over 4

=item B<enabled>

This value has to be non-zero to enable remote backups

=item B<hostname>

The hostname of the host where the remote backups will be stored

=item B<path>

The path on the remote host where the backups should be stored. Backup user must have write access.

=item B<rotations>

The number of rotations that should be stored on the remote host.

=item B<user>

The user on the remote host

=back

=head1 AUTHOR

Copyright 2001-2011 Plain Black Corporation.

=cut
